server:
  port: 8081
spring:
  application:
    name: ldm-manager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: weihao0917
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      lettuce:
        pool:
          ## 最大空闲连接数
          max-idle: 16
          ## 最大活跃连接数
          max-active: 32
          ## 最小空闲连接数
          min-idle: 8
      cache:
        type: redis
        redis:
          ## 是否缓存空值 防止缓存穿透
          cache-null-values: true
          ## 加随机时间防止缓存雪崩
          time-to-live: 360000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
## mybatis的自定义mapper xml路径
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
security:
  jwt:
    secretKey: ldmxiaodu
    ttlMillis: 7200
    tokenHeader: token

