DROP TABLE IF EXISTS sys_user;
CREATE TABLE sys_user(
    `USER_ID` INT AUTO_INCREMENT COMMENT '用户ID' ,
    `USER_NAME` VARCHAR(90) NOT NULL  COMMENT '用户登录账号' ,
    `PASSWORD` VARCHAR(90) NOT NULL  COMMENT '用户密码' ,
    `REAL_NAME` VARCHAR(90) NOT NULL  COMMENT '用户姓名' ,
    `STATUS` VARCHAR(1)   COMMENT '状态' ,
    `EMAIL` VARCHAR(90)   COMMENT '邮箱地址' ,
    `MOBILE` VARCHAR(90)   COMMENT '联系方式' ,
    `CREATED_BY` VARCHAR(90)   COMMENT '创建人' ,
    `CREATED_TIME` DATETIME   COMMENT '创建时间' ,
    `UPDATED_BY` VARCHAR(90)   COMMENT '更新人' ,
    `UPDATED_TIME` DATETIME   COMMENT '更新时间' ,
    PRIMARY KEY (USER_ID)
)  COMMENT = '用户信息表';

DROP TABLE IF EXISTS sys_role;
CREATE TABLE sys_role(
    `ROLE_ID` INT AUTO_INCREMENT COMMENT '角色ID' ,
    `ROLE_NAME` VARCHAR(90) NOT NULL  COMMENT '角色名称' ,
    `STATUS` VARCHAR(1) NOT NULL  COMMENT '状态' ,
    `CREATED_BY` VARCHAR(90)   COMMENT '创建人' ,
    `CREATED_TIME` DATETIME   COMMENT '创建时间' ,
    `UPDATED_BY` VARCHAR(90)   COMMENT '更新人' ,
    `UPDATED_TIME` DATETIME   COMMENT '更新时间' ,
    PRIMARY KEY (ROLE_ID)
)  COMMENT = '角色信息表';

DROP TABLE IF EXISTS sys_user_role;
CREATE TABLE sys_user_role(
    `ID` INT AUTO_INCREMENT COMMENT '关系ID' ,
    `USER_ID` INT NOT NULL  COMMENT '用户ID' ,
    `ROLE_ID` INT NOT NULL  COMMENT '角色ID' ,
    `CREATED_BY` VARCHAR(90)   COMMENT '创建人' ,
    `CREATED_TIME` DATETIME   COMMENT '创建时间' ,
    `UPDATED_BY` VARCHAR(90)   COMMENT '更新人' ,
    `UPDATED_TIME` DATETIME   COMMENT '更新时间' ,
    PRIMARY KEY (ID)
)  COMMENT = '用户角色关联表';

DROP TABLE IF EXISTS sys_menu;
CREATE TABLE sys_menu(
    `MENU_ID` INT AUTO_INCREMENT COMMENT '菜单ID' ,
    `PARENT_ID` INT   COMMENT '父级菜单ID' ,
    `MENU_NAME` VARCHAR(90)   COMMENT '菜单名称' ,
    `COMPONENT` VARCHAR(90)   COMMENT '组件' ,
    `VISIBLE` VARCHAR(1)   COMMENT '是否可见' ,
    `CREATED_BY` VARCHAR(32)   COMMENT '创建人' ,
    `CREATED_TIME` DATETIME   COMMENT '创建时间' ,
    PRIMARY KEY (MENU_ID)
)  COMMENT = '菜单信息表';

DROP TABLE IF EXISTS sys_role_menu;
CREATE TABLE sys_role_menu(
    `ROLE_MENU_ID` INT AUTO_INCREMENT COMMENT '角色菜单ID' ,
    `ROLE_ID` INT   COMMENT '角色ID' ,
    `MENU_ID` INT   COMMENT '菜单ID' ,
    PRIMARY KEY (ROLE_MENU_ID)
)  COMMENT = '角色菜单绑定表';
